import pandas as pd

data = [
    ["Naruto", "adventure ninja action friendship shounen", 8.2],
    ["Naruto Shippuden", "advanced ninja battles war emotions", 8.7],
    ["One Piece", "adventure pirate treasure friendship action", 8.9],
    ["Dragon Ball Z", "action power battles aliens martial arts", 8.4],
    ["Dragon Ball Super", "action gods multiverse power battles", 8.0],
    ["Bleach", "soul reapers swords supernatural battles", 8.1],
    ["Attack on Titan", "dark action survival fantasy war", 9.1],
    ["Demon Slayer", "action demons sword family revenge", 8.6],
    ["Death Note", "psychological thriller intelligence mind games", 9.0],
    ["Jujutsu Kaisen", "curses sorcerers dark action supernatural", 8.5],
    ["Black Clover", "magic rivalry fantasy adventure battles", 8.2],
    ["My Hero Academia", "superheroes academy action friendship", 8.3],
    ["Hunter x Hunter", "adventure strategy battles friendship", 8.9],
    ["One Punch Man", "superhero parody action comedy", 8.8],
    ["Tokyo Ghoul", "dark psychological horror identity conflict", 8.0],
    ["Sword Art Online", "virtual reality survival romance action", 7.8],
    ["Fairy Tail", "magic guild friendship adventure", 7.9],
    ["Fullmetal Alchemist Brotherhood", "alchemy brothers war philosophy action", 9.1],
    ["Steins Gate", "time travel science thriller emotions", 9.1],
    ["Re Zero", "fantasy time loop survival psychology", 8.3],
    ["Tokyo Revengers", "time travel gangs drama action", 8.1],
    ["Vinland Saga", "vikings revenge war historical drama", 8.8],
    ["Chainsaw Man", "dark action horror devil hunting", 8.6],
    ["Spy x Family", "spy comedy family action slice of life", 8.4],
    ["Dr Stone", "science survival civilization rebuilding", 8.2],
    ["Haikyuu", "volleyball sports teamwork motivation", 8.7],
    ["Blue Lock", "football competition psychology sports", 8.1],
    ["Cowboy Bebop", "space bounty hunters jazz action", 8.9],
    ["Code Geass", "mecha strategy rebellion intelligence", 8.9],
    ["Berserk", "dark fantasy medieval psychological violence", 9.0],
    ["Gintama", "comedy parody action samurai", 8.8],
    ["JoJo Bizarre Adventure", "supernatural battles generational action", 8.6],
    ["Mob Psycho 100", "psychic powers comedy emotional growth", 8.6],
    ["Parasyte", "alien invasion horror psychological action", 8.4],
    ["Erased", "time travel mystery crime drama", 8.5],
    ["Death Parade", "afterlife psychology games emotions", 8.3],
    ["Angel Beats", "afterlife school emotions comedy", 8.1],
    ["Clannad After Story", "romance family emotional drama", 9.0],
    ["Your Lie in April", "music romance tragedy emotions", 8.7],
    ["Horimiya", "romance slice of life school drama", 8.2],
    ["Kaguya Sama Love is War", "romantic comedy mind games school", 8.6],
    ["Monster", "psychological crime thriller mind games", 9.0],
    ["Psycho Pass", "futuristic crime psychology thriller", 8.5],
    ["Akame ga Kill", "assassins dark fantasy tragedy action", 7.9],
    ["Noragami", "gods spirits urban action comedy", 8.0],
    ["Fire Force", "firefighters supernatural action mystery", 7.9],
    ["Black Lagoon", "crime guns mercenaries action", 8.4],
    ["Dororo", "demons samurai dark fantasy revenge", 8.3],
    ["Zom 100", "zombie apocalypse comedy survival", 8.1],
    ["Devilman Crybaby", "psychological dark fantasy emotions", 8.0],
    ["Cyberpunk Edgerunners", "futuristic dystopia crime action", 8.6],
    ["A Silent Voice", "bullying redemption emotional drama", 8.9],
    ["Weathering With You", "romance fantasy weather emotions", 8.3],
    ["Suzume", "fantasy adventure disaster healing", 8.2],
    ["Spirited Away", "fantasy spirits adventure growth", 9.0],
    ["Howls Moving Castle", "fantasy romance magic adventure", 8.7],
    ["Princess Mononoke", "fantasy nature war philosophy", 8.8],
        ["Neon Genesis Evangelion", "mecha psychology existential trauma", 8.5],
    ["Samurai Champloo", "samurai hip hop action adventure", 8.7],
    ["Hellsing Ultimate", "vampires dark action horror", 8.4],
    ["Made in Abyss", "dark adventure mystery fantasy", 8.7],
    ["Great Teacher Onizuka", "school comedy life lessons drama", 8.5],
    ["Perfect Blue", "psychological thriller identity horror", 8.4],
    ["Paprika", "dream psychology sci fi thriller", 8.3],
    ["Akira", "cyberpunk psychic dystopia action", 8.6],
    ["Ghost in the Shell", "cyberpunk philosophy artificial intelligence", 8.7],
    ["FLCL", "coming of age surreal comedy action", 8.0],
    ["Kill la Kill", "action parody fashion battles", 8.1],
    ["Little Witch Academia", "magic school fantasy friendship", 7.9],
    ["Bungo Stray Dogs", "detective agency powers literature action", 8.2],
    ["Beastars", "anthropomorphic animals drama psychology", 8.1],
    ["91 Days", "mafia revenge crime drama", 8.2],
    ["Ergo Proxy", "cyberpunk philosophy dystopian mystery", 8.0],
    ["Serial Experiments Lain", "psychological cyberpunk identity", 8.1],
    ["Texhnolyze", "dark cyberpunk existential violence", 7.9],
    ["Ping Pong the Animation", "sports psychology growth competition", 8.6],
    ["Kaiji", "gambling psychological survival drama", 8.3],
    ["Golden Kamuy", "historical survival treasure adventure", 8.4],
    ["Odd Taxi", "crime mystery dialogue driven drama", 8.6],
    ["Ranking of Kings", "fantasy growth courage adventure", 8.5],
    ["Pluto", "robot ethics mystery thriller", 8.7],
    ["Heavenly Delusion", "post apocalyptic mystery survival", 8.2],
    ["Land of the Lustrous", "fantasy identity transformation drama", 8.4],
    ["Grave of the Fireflies", "war tragedy emotional survival", 9.0],
    ["Redline", "high speed racing sci fi action", 8.1],
    ["Space Dandy", "space comedy episodic adventure", 8.3],
    ["Violet Evergarden", "emotional healing letters drama", 8.8],

]

df = pd.DataFrame(data, columns=["name", "description", "rating"])
df.to_csv("data/anime.csv", index=False)

print(f"✅ {len(df)} anime entries created successfully!")
